(function() {var implementors = {};
implementors['image'] = ["<a class='stability Unmarked' title='No stability level'></a>impl&lt;T: <a class='trait' href='image/trait.Primitive.html' title='image::Primitive'>Primitive</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Index.html' title='core::ops::Index'>Index</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.uint.html'>uint</a>, T&gt; for <a class='struct' href='image/struct.Rgb.html' title='image::Rgb'>Rgb</a>&lt;T&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;T: <a class='trait' href='image/trait.Primitive.html' title='image::Primitive'>Primitive</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Index.html' title='core::ops::Index'>Index</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.uint.html'>uint</a>, T&gt; for <a class='struct' href='image/struct.Luma.html' title='image::Luma'>Luma</a>&lt;T&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;T: <a class='trait' href='image/trait.Primitive.html' title='image::Primitive'>Primitive</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Index.html' title='core::ops::Index'>Index</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.uint.html'>uint</a>, T&gt; for <a class='struct' href='image/struct.Rgba.html' title='image::Rgba'>Rgba</a>&lt;T&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;T: <a class='trait' href='image/trait.Primitive.html' title='image::Primitive'>Primitive</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Index.html' title='core::ops::Index'>Index</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.uint.html'>uint</a>, T&gt; for <a class='struct' href='image/struct.LumaA.html' title='image::LumaA'>LumaA</a>&lt;T&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;Container, T, PixelType&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Index.html' title='core::ops::Index'>Index</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.tuple.html'>(<a href='http://doc.rust-lang.org/nightly/std/primitive.u32.html'>u32</a>, <a href='http://doc.rust-lang.org/nightly/std/primitive.u32.html'>u32</a>)</a>, PixelType&gt; for <a class='struct' href='image/struct.ImageBuffer.html' title='image::ImageBuffer'>ImageBuffer</a>&lt;Container, T, PixelType&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
